name: BugReportPlugin
version: 1.0
main: com.yourname.bugreport.BugReporterPlugin
api-version: 1.21.4
commands:
  bug:
    description: Start a bug report questionnaire.
  fix:
    description: (Discord-only) Mark a bug as fixed.
  reward:
    description: (Discord-only) Reward a user for a bug fix.
